-- Run to fill APPRAISAL table with sample data
INSERT INTO APPRAISAL (ID, PROPERTY_ADDRESS, CITY, STATE, ZIP_CODE, BORROWER, OWNER_OF_PUBLIC_RECORD, COUNTY)
VALUES (0, '123 Fake St', 'Anytown', 'ZZ', '00000', 'John Doe', 'Jane Doe');
