-- Run to fill APPRAISAL table with sample data
INSERT INTO APPRAISAL (ID, PROPERTY_ADDRESS, CITY, STATE, ZIP_CODE, BORROWER, OWNER_OF_PUBLIC_RECORD, COUNTY)
VALUES (1, '123 Fake St', 'Anytown', 'ZZ', '00000', 'John Doe', 'Jane Doe', 'FakeCounty');

INSERT INTO APPRAISAL (ID, PROPERTY_ADDRESS, CITY, STATE, ZIP_CODE, BORROWER, OWNER_OF_PUBLIC_RECORD, COUNTY)
VALUES (2, '124 Fake St', 'Anytown', 'ZZ', '00000', 'Bob Doe', 'Betty Doe', 'FakeCounty');
